### PR TITLE
update to use pulumi-kuberentes 2.0+ and kubernetes client-go 1.18

### LINKED ISSUE #70: Update to use Pulumi 2.0 modules
This will require some changes to the `watch` package.

### PR DESCRIPTION
**Pull request by nicks**
Hi! I'm giving a talk at Kubecon in November. A section of it discusses some things I admire about how kubespy uses client-go. 

In order to show this off, it would help me a lot if this was on a newer version of client-go!

I saw you had an issue open about upgrading modules (https://github.com/pulumi/kubespy/issues/70), so I took the liberty of sending a PR. I'm not sure how opinionated this code is about use of the kubernetes client and open to change it.

Thanks!

Fix #70

### CODE REVIEW

**Comment by stack72** [comment]
Hi @nicks 

We will get this reviewed / testing / merged and released before your talk!

Thanks so much for doing this

Paul

**Comment by lblackstone** [comment]
Hey @nicks, thanks for the PR! I PR'd a small change to your branch and spot-checked it locally. LGTM once https://github.com/tilt-dev/kubespy/pull/1 lands

**Comment by nicks** [comment]
updated!

**Review by lblackstone — APPROVED** [review]

**Comment by lblackstone** [comment]
@nicks I cut a new release that includes this change: https://github.com/pulumi/kubespy/releases/tag/v0.6.0

**Pull request merged**
