### PR TITLE
Switch from dep to Go modules

### PR DESCRIPTION
**Pull request by ambientsound**
Golang 1.11 introduces the concept of _modules_, which deprecates all other Go package managers.

https://github.com/golang/go/wiki/Modules

### CODE REVIEW

**Comment by hausdorff** [comment]
Oh sick, thanks for the PR.

I'm curious, though: kubernetes/client-go is notoriously awful to deal with, even using `dep`, and certainly using (_e.g._) `govendor`. ([_cf_](https://medium.com/@andy.goldstein/upgrading-kubernetes-client-go-from-v4-to-v5-bbd5025fe381)., [_cf_](https://medium.com/@vladimirvivien/using-gos-dep-to-organize-your-kubernetes-client-go-dependencies-509ddc766ed3)., [_cf_](https://blog.heptio.com/straighten-out-your-kubernetes-client-go-dependencies-heptioprotip-8baeed46fe7d).). So while I'm personally inclined to be on the bleeding edge of stuff, I'm a bit worried that the k8s client libraries themselves are not quite ready for this.

Thoughts? I know comparatively little about this, so I'd be happy to hear a dissenting opinion.

**Comment by ambientsound** [comment]
Go modules works both with libraries that are _ready_ for modules, and libraries that don't support that yet. It will scan the repository for other kinds of lock files (e.g, dep or Glide or govendor) and parse out the version requirement. Ultimately, Go modules will fall back on Git HEAD. In either case, the exact versions for the build will be recorded in the `go.mod` file, and they will not change or bump unless you explicitly ask to.

Personally, a huge problem with depending on the Kubernetes client library has been conflicts with other Go projects living on my workstation. Go modules solves this elegantly by placing all dependencies in `$GOPATH/pkg/` and suffixing them with the package version. Thus, multiple versions can live on your file system concurrently.

My team uses Go modules in our [custom operator](https://github.com/nais/naiserator), and it's been a smooth ride so far.

**Comment by hausdorff** [comment]
Ah, what the heck, `kubespy` is the product of the Fun and Playtime Division here at PulumiCorp. And what is the point of such a division if we are not having fun and doing playtime? I'll look at integrating it later today.

I am a bit worried about what upgrading looks like, but we can always go back.

**Comment by liftedkilt** [comment]
I think it's broken...at least I can't get it to build. And `go build` keeps changing my go.mod file, which is annoying

**Comment by hausdorff** [comment]
@liftedkilt hmm, that sucks. Can you open an issue with more details?

**Pull request merged**
